from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .collect import collect_inventory, write_json
from .sanitize import assert_public_safe, build_public_snapshot


def render_public_markdown(snapshot: dict[str, Any]) -> str:
    system = snapshot.get("system", {})
    session = snapshot.get("session", {})
    graphics = snapshot.get("graphics", {})

    lines = [
        "# GM107 Reference Platform",
        "",
        "> Generated by `maxwell-lab characterize`. This file contains only allowlisted",
        "> hardware/software fields. Raw inventory data must remain in `artifacts/`.",
        "",
        "## System",
        "",
    ]

    labels = (
        ("OS", system.get("os")),
        ("Kernel", system.get("kernel")),
        ("Architecture", system.get("architecture")),
        ("System vendor", system.get("system_vendor")),
        ("Product", system.get("product_name")),
        ("Product version", system.get("product_version")),
        ("BIOS vendor", system.get("bios_vendor")),
        ("BIOS version", system.get("bios_version")),
        ("BIOS date", system.get("bios_date")),
        ("CPU", system.get("cpu_model")),
    )
    for label, value in labels:
        if value not in (None, ""):
            lines.append(f"- **{label}:** {value}")

    memory_kib = system.get("memory_total_kib")
    if isinstance(memory_kib, int):
        lines.append(f"- **Memory:** {memory_kib / 1024 / 1024:.1f} GiB")

    if session:
        lines.extend(["", "## Session", ""])
        if session.get("type"):
            lines.append(f"- **Type:** {session['type']}")
        if session.get("desktop"):
            lines.append(f"- **Desktop:** {session['desktop']}")

    blocks = graphics.get("pci_graphics_blocks", [])
    if blocks:
        lines.extend(["", "## Graphics PCI topology", "", "```text"])
        lines.extend(blocks)
        lines.append("```")

    drm_devices = graphics.get("drm_devices", [])
    if drm_devices:
        lines.extend(["", "## DRM devices", "", "```json"])
        lines.append(json.dumps(drm_devices, indent=2, sort_keys=True))
        lines.append("```")

    drm_connectors = graphics.get("drm_connectors", [])
    if drm_connectors:
        lines.extend(["", "## DRM connectors", "", "```json"])
        lines.append(json.dumps(drm_connectors, indent=2, sort_keys=True))
        lines.append("```")

    for title, key in (("Vulkan", "vulkan"), ("OpenGL", "opengl")):
        values = graphics.get(key, [])
        if values:
            lines.extend(["", f"## {title}", "", "```text"])
            lines.extend(values)
            lines.append("```")

    if graphics.get("nvidia_smi"):
        lines.extend([
            "",
            "## NVIDIA proprietary-driver telemetry",
            "",
            "```text",
            graphics["nvidia_smi"],
            "```",
        ])

    if graphics.get("nouveau_pstates"):
        lines.extend(["", "## Nouveau performance states", "", "```json"])
        lines.append(json.dumps(graphics["nouveau_pstates"], indent=2, sort_keys=True))
        lines.append("```")

    if graphics.get("nvidia_pci_runtime_pm"):
        lines.extend(["", "## NVIDIA PCI runtime PM", "", "```json"])
        lines.append(json.dumps(graphics["nvidia_pci_runtime_pm"], indent=2, sort_keys=True))
        lines.append("```")

    if graphics.get("prime_providers"):
        lines.extend([
            "",
            "## PRIME providers",
            "",
            "```text",
            graphics["prime_providers"],
            "```",
        ])

    lines.extend([
        "",
        "## Privacy",
        "",
        "Raw inventory is intentionally excluded from Git. Do not add serial numbers,",
        "UUIDs, MAC addresses, hostnames, usernames, home-directory paths, EDID blobs,",
        "or unrelated system logs to this public reference file.",
        "",
    ])
    return "\n".join(lines)


def characterize(*, output_dir: Path, public_output: Path | None = None) -> dict[str, Path]:
    raw = collect_inventory(include_hostname=False)
    snapshot = build_public_snapshot(raw)
    markdown = render_public_markdown(snapshot)

    public_json_text = json.dumps(snapshot, indent=2, sort_keys=True) + "\n"
    assert_public_safe(public_json_text, inventory=raw)
    assert_public_safe(markdown, inventory=raw)

    raw_path = output_dir / "raw" / "inventory.json"
    public_json_path = output_dir / "public" / "inventory.public.json"
    public_md_path = output_dir / "public" / "summary.md"

    write_json(raw_path, raw)
    write_json(public_json_path, snapshot)
    public_md_path.parent.mkdir(parents=True, exist_ok=True)
    public_md_path.write_text(markdown, encoding="utf-8")

    outputs = {
        "raw_inventory": raw_path,
        "public_inventory": public_json_path,
        "public_summary": public_md_path,
    }

    if public_output is not None:
        public_output.parent.mkdir(parents=True, exist_ok=True)
        public_output.write_text(markdown, encoding="utf-8")
        outputs["requested_public_summary"] = public_output

    return outputs
